apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
    ### Create a name for your PVC ###
    name: esa-pvc
    ### Use a namespace that matched your intended consuming pod, or "default" ###
    namespace: default
spec: 
    accessModes: 
        - ReadWriteMany 
    resources: 
        requests: 
            storage: 5Gi 
    storageClassName: esa
    volumeMode: Filesystem
    volumeName: esa-pv
status: 
    accessModes: 
        - ReadWriteMany 
    capacity: 
        storage: 5Gi